CREATE TABLE IF NOT EXISTS listings(
    street_address CHAR (100),
    area DECIMAL,
    attrs JSON,
    available DATE,
    bathrooms DECIMAL,
    bedrooms DECIMAL,
    body VARCHAR (10000),
    cats_ok BOOLEAN,
    created TIMESTAMP,
    extracted TIMESTAMP,
    deleted TIMESTAMP,
    dogs_ok BOOLEAN,
    ev_charging BOOLEAN,
    geotag JSON,
    housing_type VARCHAR(25),
    id INT UNSIGNED PRIMARY KEY,
    images JSON,
    is_furnished BOOLEAN,
    last_updated TIMESTAMP,
    laundry VARCHAR(25),
    title VARCHAR(200),
    no_smoking BOOLEAN,
    parking VARCHAR(25),
    price DECIMAL,
    repost_of INT UNSIGNED,
    listing_url VARCHAR(200),
    wheelchair_access BOOLEAN,
    neighborhood VARCHAR(100) flagged BOOLEAN,
    deleted BOOLEAN,
    week_flagged DATE,
    week_deleted DATE
);

CREATE TABLE IF NOT EXISTS locations(
    geotag JSON PRIMARY KEY,
    latitude DECIMAL,
    longitude DECIMAL,
    google_maps_address JSON,
    zipcode CHAR(5),
    us_state CHAR(2)
);